package com.me2me.search.mapper;

import com.me2me.search.model.HotKeyword;
import com.me2me.search.model.HotKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    int countByExample(HotKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    int deleteByExample(HotKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    int insert(HotKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    int insertSelective(HotKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    List<HotKeyword> selectByExample(HotKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    HotKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") HotKeyword record, @Param("example") HotKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    int updateByExample(@Param("record") HotKeyword record, @Param("example") HotKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    int updateByPrimaryKeySelective(HotKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    int updateByPrimaryKey(HotKeyword record);
}