package com.me2me.user.model;

import com.me2me.common.web.BaseEntity;

public class AppConfig implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_config.id
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_config.name
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_config.config_key
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    private String configKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_config.config_value
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    private String configValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_config.id
     *
     * @return the value of app_config.id
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_config.id
     *
     * @param id the value for app_config.id
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_config.name
     *
     * @return the value of app_config.name
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_config.name
     *
     * @param name the value for app_config.name
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_config.config_key
     *
     * @return the value of app_config.config_key
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_config.config_key
     *
     * @param configKey the value for app_config.config_key
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_config.config_value
     *
     * @return the value of app_config.config_value
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_config.config_value
     *
     * @param configValue the value for app_config.config_value
     *
     * @mbggenerated Wed Jun 07 11:29:49 CST 2017
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }
}