package com.me2me.user.model;

import java.util.Date;

import com.me2me.common.web.BaseEntity;

public class EmotionInfo  implements BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.id
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.emotionName
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private String emotionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.happyMin
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private Integer happymin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.happyMax
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private Integer happymax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.freeMin
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private Integer freemin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.freeMax
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private Integer freemax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.emotionPackId
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private Long emotionpackid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.topicId
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private Long topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.status
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_info.create_time
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.id
     *
     * @return the value of emotion_info.id
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.id
     *
     * @param id the value for emotion_info.id
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.emotionName
     *
     * @return the value of emotion_info.emotionName
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public String getEmotionname() {
        return emotionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.emotionName
     *
     * @param emotionname the value for emotion_info.emotionName
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setEmotionname(String emotionname) {
        this.emotionname = emotionname == null ? null : emotionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.happyMin
     *
     * @return the value of emotion_info.happyMin
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public Integer getHappymin() {
        return happymin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.happyMin
     *
     * @param happymin the value for emotion_info.happyMin
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setHappymin(Integer happymin) {
        this.happymin = happymin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.happyMax
     *
     * @return the value of emotion_info.happyMax
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public Integer getHappymax() {
        return happymax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.happyMax
     *
     * @param happymax the value for emotion_info.happyMax
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setHappymax(Integer happymax) {
        this.happymax = happymax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.freeMin
     *
     * @return the value of emotion_info.freeMin
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public Integer getFreemin() {
        return freemin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.freeMin
     *
     * @param freemin the value for emotion_info.freeMin
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setFreemin(Integer freemin) {
        this.freemin = freemin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.freeMax
     *
     * @return the value of emotion_info.freeMax
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public Integer getFreemax() {
        return freemax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.freeMax
     *
     * @param freemax the value for emotion_info.freeMax
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setFreemax(Integer freemax) {
        this.freemax = freemax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.emotionPackId
     *
     * @return the value of emotion_info.emotionPackId
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public Long getEmotionpackid() {
        return emotionpackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.emotionPackId
     *
     * @param emotionpackid the value for emotion_info.emotionPackId
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setEmotionpackid(Long emotionpackid) {
        this.emotionpackid = emotionpackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.topicId
     *
     * @return the value of emotion_info.topicId
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public Long getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.topicId
     *
     * @param topicid the value for emotion_info.topicId
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setTopicid(Long topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.status
     *
     * @return the value of emotion_info.status
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.status
     *
     * @param status the value for emotion_info.status
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_info.create_time
     *
     * @return the value of emotion_info.create_time
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_info.create_time
     *
     * @param createTime the value for emotion_info.create_time
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}