package com.me2me.user.model;

public class SystemConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.id
     *
     * @mbggenerated Fri Oct 28 17:37:40 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.default_follow
     *
     * @mbggenerated Fri Oct 28 17:37:40 CST 2016
     */
    private Long defaultFollow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.id
     *
     * @return the value of system_config.id
     *
     * @mbggenerated Fri Oct 28 17:37:40 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.id
     *
     * @param id the value for system_config.id
     *
     * @mbggenerated Fri Oct 28 17:37:40 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.default_follow
     *
     * @return the value of system_config.default_follow
     *
     * @mbggenerated Fri Oct 28 17:37:40 CST 2016
     */
    public Long getDefaultFollow() {
        return defaultFollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.default_follow
     *
     * @param defaultFollow the value for system_config.default_follow
     *
     * @mbggenerated Fri Oct 28 17:37:40 CST 2016
     */
    public void setDefaultFollow(Long defaultFollow) {
        this.defaultFollow = defaultFollow;
    }
}