package com.me2me.user.model;

import com.me2me.common.web.BaseEntity;

public class SystemConfig implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.id
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.default_follow
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    private Long defaultFollow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.read_count_start
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    private Integer readCountStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.read_count_end
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    private Integer readCountEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.id
     *
     * @return the value of system_config.id
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.id
     *
     * @param id the value for system_config.id
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.default_follow
     *
     * @return the value of system_config.default_follow
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    public Long getDefaultFollow() {
        return defaultFollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.default_follow
     *
     * @param defaultFollow the value for system_config.default_follow
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    public void setDefaultFollow(Long defaultFollow) {
        this.defaultFollow = defaultFollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.read_count_start
     *
     * @return the value of system_config.read_count_start
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    public Integer getReadCountStart() {
        return readCountStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.read_count_start
     *
     * @param readCountStart the value for system_config.read_count_start
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    public void setReadCountStart(Integer readCountStart) {
        this.readCountStart = readCountStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.read_count_end
     *
     * @return the value of system_config.read_count_end
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    public Integer getReadCountEnd() {
        return readCountEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.read_count_end
     *
     * @param readCountEnd the value for system_config.read_count_end
     *
     * @mbggenerated Wed Nov 02 18:23:19 CST 2016
     */
    public void setReadCountEnd(Integer readCountEnd) {
        this.readCountEnd = readCountEnd;
    }
}