package com.me2me.user.model;

import java.util.Date;

import com.me2me.common.web.BaseEntity;

public class UserLastChannel implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_last_channel.id
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_last_channel.uid
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_last_channel.channel
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_last_channel.login_time
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_last_channel.id
     *
     * @return the value of user_last_channel.id
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_last_channel.id
     *
     * @param id the value for user_last_channel.id
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_last_channel.uid
     *
     * @return the value of user_last_channel.uid
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_last_channel.uid
     *
     * @param uid the value for user_last_channel.uid
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_last_channel.channel
     *
     * @return the value of user_last_channel.channel
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_last_channel.channel
     *
     * @param channel the value for user_last_channel.channel
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_last_channel.login_time
     *
     * @return the value of user_last_channel.login_time
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_last_channel.login_time
     *
     * @param loginTime the value for user_last_channel.login_time
     *
     * @mbggenerated Fri Oct 27 15:59:48 CST 2017
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}