package com.me2me.user.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class UserProfile implements BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.id
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.uid
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.mobile
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.nick_name
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.gender
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.birthday
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.avatar
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.years_id
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Long yearsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.star_id
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Long starId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.social_class
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Long socialClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.industry
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Long industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.marriage_status
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Long marriageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.bear_status
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Long bearStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.create_time
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.update_time
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.id
     *
     * @return the value of user_profile.id
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.id
     *
     * @param id the value for user_profile.id
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.uid
     *
     * @return the value of user_profile.uid
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.uid
     *
     * @param uid the value for user_profile.uid
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.mobile
     *
     * @return the value of user_profile.mobile
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.mobile
     *
     * @param mobile the value for user_profile.mobile
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.nick_name
     *
     * @return the value of user_profile.nick_name
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.nick_name
     *
     * @param nickName the value for user_profile.nick_name
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.gender
     *
     * @return the value of user_profile.gender
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.gender
     *
     * @param gender the value for user_profile.gender
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.birthday
     *
     * @return the value of user_profile.birthday
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.birthday
     *
     * @param birthday the value for user_profile.birthday
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.avatar
     *
     * @return the value of user_profile.avatar
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.avatar
     *
     * @param avatar the value for user_profile.avatar
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.years_id
     *
     * @return the value of user_profile.years_id
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Long getYearsId() {
        return yearsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.years_id
     *
     * @param yearsId the value for user_profile.years_id
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setYearsId(Long yearsId) {
        this.yearsId = yearsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.star_id
     *
     * @return the value of user_profile.star_id
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Long getStarId() {
        return starId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.star_id
     *
     * @param starId the value for user_profile.star_id
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setStarId(Long starId) {
        this.starId = starId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.social_class
     *
     * @return the value of user_profile.social_class
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Long getSocialClass() {
        return socialClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.social_class
     *
     * @param socialClass the value for user_profile.social_class
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setSocialClass(Long socialClass) {
        this.socialClass = socialClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.industry
     *
     * @return the value of user_profile.industry
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Long getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.industry
     *
     * @param industry the value for user_profile.industry
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setIndustry(Long industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.marriage_status
     *
     * @return the value of user_profile.marriage_status
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Long getMarriageStatus() {
        return marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.marriage_status
     *
     * @param marriageStatus the value for user_profile.marriage_status
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setMarriageStatus(Long marriageStatus) {
        this.marriageStatus = marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.bear_status
     *
     * @return the value of user_profile.bear_status
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Long getBearStatus() {
        return bearStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.bear_status
     *
     * @param bearStatus the value for user_profile.bear_status
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setBearStatus(Long bearStatus) {
        this.bearStatus = bearStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.create_time
     *
     * @return the value of user_profile.create_time
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.create_time
     *
     * @param createTime the value for user_profile.create_time
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.update_time
     *
     * @return the value of user_profile.update_time
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.update_time
     *
     * @param updateTime the value for user_profile.update_time
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}