package com.me2me.user.model;

public class UserTagsDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tags_details.id
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tags_details.tid
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tags_details.uid
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tags_details.fuid
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    private Long fuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tags_details.id
     *
     * @return the value of user_tags_details.id
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tags_details.id
     *
     * @param id the value for user_tags_details.id
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tags_details.tid
     *
     * @return the value of user_tags_details.tid
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tags_details.tid
     *
     * @param tid the value for user_tags_details.tid
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tags_details.uid
     *
     * @return the value of user_tags_details.uid
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tags_details.uid
     *
     * @param uid the value for user_tags_details.uid
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tags_details.fuid
     *
     * @return the value of user_tags_details.fuid
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    public Long getFuid() {
        return fuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tags_details.fuid
     *
     * @param fuid the value for user_tags_details.fuid
     *
     * @mbggenerated Fri Mar 25 10:22:32 CST 2016
     */
    public void setFuid(Long fuid) {
        this.fuid = fuid;
    }
}