package com.me2me.content.model;

public class ContentTagLikes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tag_likes.id
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tag_likes.tag_id
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tag_likes.cid
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tag_likes.uid
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tag_likes.id
     *
     * @return the value of content_tag_likes.id
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tag_likes.id
     *
     * @param id the value for content_tag_likes.id
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tag_likes.tag_id
     *
     * @return the value of content_tag_likes.tag_id
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tag_likes.tag_id
     *
     * @param tagId the value for content_tag_likes.tag_id
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tag_likes.cid
     *
     * @return the value of content_tag_likes.cid
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tag_likes.cid
     *
     * @param cid the value for content_tag_likes.cid
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tag_likes.uid
     *
     * @return the value of content_tag_likes.uid
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tag_likes.uid
     *
     * @param uid the value for content_tag_likes.uid
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}