package com.me2me.content.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class Content implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.id
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.uid
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.forward_cid
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Long forwardCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.title
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.feeling
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private String feeling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.type
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.conver_image
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private String converImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.forward_title
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private String forwardTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.forward_url
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private String forwardUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.content_type
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.thumbnail
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private String thumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.hot_value
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer hotValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.person_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer personCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.review_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer reviewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.like_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.favorite_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer favoriteCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.read_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer readCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.read_count_dummy
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer readCountDummy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.is_top
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.authorization
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer authorization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.rights
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer rights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.author
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.status
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.create_time
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.content
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.id
     *
     * @return the value of content.id
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.id
     *
     * @param id the value for content.id
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.uid
     *
     * @return the value of content.uid
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.uid
     *
     * @param uid the value for content.uid
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.forward_cid
     *
     * @return the value of content.forward_cid
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Long getForwardCid() {
        return forwardCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.forward_cid
     *
     * @param forwardCid the value for content.forward_cid
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setForwardCid(Long forwardCid) {
        this.forwardCid = forwardCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.title
     *
     * @return the value of content.title
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.title
     *
     * @param title the value for content.title
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.feeling
     *
     * @return the value of content.feeling
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public String getFeeling() {
        return feeling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.feeling
     *
     * @param feeling the value for content.feeling
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setFeeling(String feeling) {
        this.feeling = feeling == null ? null : feeling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.type
     *
     * @return the value of content.type
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.type
     *
     * @param type the value for content.type
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.conver_image
     *
     * @return the value of content.conver_image
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public String getConverImage() {
        return converImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.conver_image
     *
     * @param converImage the value for content.conver_image
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setConverImage(String converImage) {
        this.converImage = converImage == null ? null : converImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.forward_title
     *
     * @return the value of content.forward_title
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public String getForwardTitle() {
        return forwardTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.forward_title
     *
     * @param forwardTitle the value for content.forward_title
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setForwardTitle(String forwardTitle) {
        this.forwardTitle = forwardTitle == null ? null : forwardTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.forward_url
     *
     * @return the value of content.forward_url
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public String getForwardUrl() {
        return forwardUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.forward_url
     *
     * @param forwardUrl the value for content.forward_url
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setForwardUrl(String forwardUrl) {
        this.forwardUrl = forwardUrl == null ? null : forwardUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.content_type
     *
     * @return the value of content.content_type
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.content_type
     *
     * @param contentType the value for content.content_type
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.thumbnail
     *
     * @return the value of content.thumbnail
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.thumbnail
     *
     * @param thumbnail the value for content.thumbnail
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.hot_value
     *
     * @return the value of content.hot_value
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getHotValue() {
        return hotValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.hot_value
     *
     * @param hotValue the value for content.hot_value
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setHotValue(Integer hotValue) {
        this.hotValue = hotValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.person_count
     *
     * @return the value of content.person_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getPersonCount() {
        return personCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.person_count
     *
     * @param personCount the value for content.person_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setPersonCount(Integer personCount) {
        this.personCount = personCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.review_count
     *
     * @return the value of content.review_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getReviewCount() {
        return reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.review_count
     *
     * @param reviewCount the value for content.review_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setReviewCount(Integer reviewCount) {
        this.reviewCount = reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.like_count
     *
     * @return the value of content.like_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.like_count
     *
     * @param likeCount the value for content.like_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.favorite_count
     *
     * @return the value of content.favorite_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getFavoriteCount() {
        return favoriteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.favorite_count
     *
     * @param favoriteCount the value for content.favorite_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setFavoriteCount(Integer favoriteCount) {
        this.favoriteCount = favoriteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.read_count
     *
     * @return the value of content.read_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.read_count
     *
     * @param readCount the value for content.read_count
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.read_count_dummy
     *
     * @return the value of content.read_count_dummy
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getReadCountDummy() {
        return readCountDummy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.read_count_dummy
     *
     * @param readCountDummy the value for content.read_count_dummy
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setReadCountDummy(Integer readCountDummy) {
        this.readCountDummy = readCountDummy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.is_top
     *
     * @return the value of content.is_top
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.is_top
     *
     * @param isTop the value for content.is_top
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.authorization
     *
     * @return the value of content.authorization
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getAuthorization() {
        return authorization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.authorization
     *
     * @param authorization the value for content.authorization
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setAuthorization(Integer authorization) {
        this.authorization = authorization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.rights
     *
     * @return the value of content.rights
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.rights
     *
     * @param rights the value for content.rights
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setRights(Integer rights) {
        this.rights = rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.author
     *
     * @return the value of content.author
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.author
     *
     * @param author the value for content.author
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.status
     *
     * @return the value of content.status
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.status
     *
     * @param status the value for content.status
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.create_time
     *
     * @return the value of content.create_time
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.create_time
     *
     * @param createTime the value for content.create_time
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.content
     *
     * @return the value of content.content
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.content
     *
     * @param content the value for content.content
     *
     * @mbggenerated Mon Oct 31 17:56:58 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}