package com.me2me.content.model;

public class ContentTagsDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tags_details.id
     *
     * @mbggenerated Wed May 04 14:24:49 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tags_details.cid
     *
     * @mbggenerated Wed May 04 14:24:49 CST 2016
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tags_details.tid
     *
     * @mbggenerated Wed May 04 14:24:49 CST 2016
     */
    private Long tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tags_details.id
     *
     * @return the value of content_tags_details.id
     *
     * @mbggenerated Wed May 04 14:24:49 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tags_details.id
     *
     * @param id the value for content_tags_details.id
     *
     * @mbggenerated Wed May 04 14:24:49 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tags_details.cid
     *
     * @return the value of content_tags_details.cid
     *
     * @mbggenerated Wed May 04 14:24:49 CST 2016
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tags_details.cid
     *
     * @param cid the value for content_tags_details.cid
     *
     * @mbggenerated Wed May 04 14:24:49 CST 2016
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tags_details.tid
     *
     * @return the value of content_tags_details.tid
     *
     * @mbggenerated Wed May 04 14:24:49 CST 2016
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tags_details.tid
     *
     * @param tid the value for content_tags_details.tid
     *
     * @mbggenerated Wed May 04 14:24:49 CST 2016
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }
}