package com.me2me.content.mapper;

import com.me2me.content.model.ArticleReview;
import com.me2me.content.model.ArticleReviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    int countByExample(ArticleReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    int deleteByExample(ArticleReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    int insert(ArticleReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    int insertSelective(ArticleReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    List<ArticleReview> selectByExample(ArticleReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    ArticleReview selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") ArticleReview record, @Param("example") ArticleReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    int updateByExample(@Param("record") ArticleReview record, @Param("example") ArticleReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    int updateByPrimaryKeySelective(ArticleReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_review
     *
     * @mbggenerated Tue Jun 07 17:02:42 CST 2016
     */
    int updateByPrimaryKey(ArticleReview record);
}