package com.me2me.content.mapper;

import com.me2me.content.model.ContentUserLike;
import com.me2me.content.model.ContentUserLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentUserLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    int countByExample(ContentUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    int deleteByExample(ContentUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    int insert(ContentUserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    int insertSelective(ContentUserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    List<ContentUserLike> selectByExample(ContentUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    ContentUserLike selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") ContentUserLike record, @Param("example") ContentUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    int updateByExample(@Param("record") ContentUserLike record, @Param("example") ContentUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    int updateByPrimaryKeySelective(ContentUserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Thu Mar 24 13:13:20 CST 2016
     */
    int updateByPrimaryKey(ContentUserLike record);
}