package com.me2me.content.mapper;

import com.me2me.content.model.Content;
import com.me2me.content.model.ContentTagLikes;
import com.me2me.content.model.ContentTagLikesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentTagLikesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int countByExample(ContentTagLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int deleteByExample(ContentTagLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int insert(ContentTagLikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int insertSelective(ContentTagLikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    List<ContentTagLikes> selectByExample(ContentTagLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    ContentTagLikes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") ContentTagLikes record, @Param("example") ContentTagLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int updateByExample(@Param("record") ContentTagLikes record, @Param("example") ContentTagLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int updateByPrimaryKeySelective(ContentTagLikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tag_likes
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int updateByPrimaryKey(ContentTagLikes record);


    List<ContentTagLikes> getContentTagTimeline(long cid);
}