package com.me2me.content.mapper;

import com.me2me.content.dto.LoadAllFeelingDto;
import com.me2me.content.model.ContentUserLikes;
import com.me2me.content.model.ContentUserLikesExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ContentUserLikesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    int countByExample(ContentUserLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    int deleteByExample(ContentUserLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    int insert(ContentUserLikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    int insertSelective(ContentUserLikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    List<ContentUserLikes> selectByExample(ContentUserLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    ContentUserLikes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") ContentUserLikes record, @Param("example") ContentUserLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    int updateByExample(@Param("record") ContentUserLikes record, @Param("example") ContentUserLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    int updateByPrimaryKeySelective(ContentUserLikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes
     *
     * @mbggenerated Tue Mar 29 17:19:28 CST 2016
     */
    int updateByPrimaryKey(ContentUserLikes record);

    List<LoadAllFeelingDto> loadAllFeeling(Map map);
}