package com.me2me.content.mapper;

import com.me2me.content.model.ContentUserLikesCount;
import com.me2me.content.model.ContentUserLikesCountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentUserLikesCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    int countByExample(ContentUserLikesCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    int deleteByExample(ContentUserLikesCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    int insert(ContentUserLikesCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    int insertSelective(ContentUserLikesCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    List<ContentUserLikesCount> selectByExample(ContentUserLikesCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    ContentUserLikesCount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") ContentUserLikesCount record, @Param("example") ContentUserLikesCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    int updateByExample(@Param("record") ContentUserLikesCount record, @Param("example") ContentUserLikesCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    int updateByPrimaryKeySelective(ContentUserLikesCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_user_likes_count
     *
     * @mbggenerated Wed Apr 06 10:18:38 CST 2016
     */
    int updateByPrimaryKey(ContentUserLikesCount record);
}