package com.me2me.live.model;

import com.me2me.common.web.BaseEntity;

public class LiveCpi implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_cpi.id
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_cpi.topic_id
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_cpi.forward_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    private Integer forwardCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_cpi.tag_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    private Integer tagCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_cpi.review_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    private Integer reviewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_cpi.person_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    private Integer personCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_cpi.id
     *
     * @return the value of live_cpi.id
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_cpi.id
     *
     * @param id the value for live_cpi.id
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_cpi.topic_id
     *
     * @return the value of live_cpi.topic_id
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_cpi.topic_id
     *
     * @param topicId the value for live_cpi.topic_id
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_cpi.forward_count
     *
     * @return the value of live_cpi.forward_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public Integer getForwardCount() {
        return forwardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_cpi.forward_count
     *
     * @param forwardCount the value for live_cpi.forward_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public void setForwardCount(Integer forwardCount) {
        this.forwardCount = forwardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_cpi.tag_count
     *
     * @return the value of live_cpi.tag_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public Integer getTagCount() {
        return tagCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_cpi.tag_count
     *
     * @param tagCount the value for live_cpi.tag_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public void setTagCount(Integer tagCount) {
        this.tagCount = tagCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_cpi.review_count
     *
     * @return the value of live_cpi.review_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public Integer getReviewCount() {
        return reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_cpi.review_count
     *
     * @param reviewCount the value for live_cpi.review_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public void setReviewCount(Integer reviewCount) {
        this.reviewCount = reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_cpi.person_count
     *
     * @return the value of live_cpi.person_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public Integer getPersonCount() {
        return personCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_cpi.person_count
     *
     * @param personCount the value for live_cpi.person_count
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    public void setPersonCount(Integer personCount) {
        this.personCount = personCount;
    }
}