package com.me2me.live.model;

import com.me2me.common.web.BaseEntity;

public class TopicUserConfig implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_user_config.id
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_user_config.uid
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_user_config.topic_id
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_user_config.push_type
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    private Integer pushType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_user_config.id
     *
     * @return the value of topic_user_config.id
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_user_config.id
     *
     * @param id the value for topic_user_config.id
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_user_config.uid
     *
     * @return the value of topic_user_config.uid
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_user_config.uid
     *
     * @param uid the value for topic_user_config.uid
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_user_config.topic_id
     *
     * @return the value of topic_user_config.topic_id
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_user_config.topic_id
     *
     * @param topicId the value for topic_user_config.topic_id
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_user_config.push_type
     *
     * @return the value of topic_user_config.push_type
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    public Integer getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_user_config.push_type
     *
     * @param pushType the value for topic_user_config.push_type
     *
     * @mbggenerated Sun Jan 22 09:35:40 CST 2017
     */
    public void setPushType(Integer pushType) {
        this.pushType = pushType;
    }
}