package com.me2me.live.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class TopicTag implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.id
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.tag
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.is_rec
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    private Integer isRec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.is_sys
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    private Integer isSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.status
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.create_time
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.id
     *
     * @return the value of topic_tag.id
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.id
     *
     * @param id the value for topic_tag.id
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.tag
     *
     * @return the value of topic_tag.tag
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.tag
     *
     * @param tag the value for topic_tag.tag
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.is_rec
     *
     * @return the value of topic_tag.is_rec
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public Integer getIsRec() {
        return isRec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.is_rec
     *
     * @param isRec the value for topic_tag.is_rec
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public void setIsRec(Integer isRec) {
        this.isRec = isRec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.is_sys
     *
     * @return the value of topic_tag.is_sys
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public Integer getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.is_sys
     *
     * @param isSys the value for topic_tag.is_sys
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public void setIsSys(Integer isSys) {
        this.isSys = isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.status
     *
     * @return the value of topic_tag.status
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.status
     *
     * @param status the value for topic_tag.status
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.create_time
     *
     * @return the value of topic_tag.create_time
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.create_time
     *
     * @param createTime the value for topic_tag.create_time
     *
     * @mbggenerated Mon Apr 10 10:00:28 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}