package com.me2me.live.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class Topic implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.uid
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.live_image
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private String liveImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.status
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.create_time
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.update_time
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.long_time
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private Long longTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.qrcode
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private String qrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.core_circle
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    private String coreCircle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.uid
     *
     * @return the value of topic.uid
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.uid
     *
     * @param uid the value for topic.uid
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.live_image
     *
     * @return the value of topic.live_image
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public String getLiveImage() {
        return liveImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.live_image
     *
     * @param liveImage the value for topic.live_image
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setLiveImage(String liveImage) {
        this.liveImage = liveImage == null ? null : liveImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.status
     *
     * @return the value of topic.status
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.status
     *
     * @param status the value for topic.status
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.create_time
     *
     * @return the value of topic.create_time
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.create_time
     *
     * @param createTime the value for topic.create_time
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.update_time
     *
     * @return the value of topic.update_time
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.update_time
     *
     * @param updateTime the value for topic.update_time
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.long_time
     *
     * @return the value of topic.long_time
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public Long getLongTime() {
        return longTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.long_time
     *
     * @param longTime the value for topic.long_time
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setLongTime(Long longTime) {
        this.longTime = longTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.qrcode
     *
     * @return the value of topic.qrcode
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.qrcode
     *
     * @param qrcode the value for topic.qrcode
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode == null ? null : qrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.core_circle
     *
     * @return the value of topic.core_circle
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public String getCoreCircle() {
        return coreCircle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.core_circle
     *
     * @param coreCircle the value for topic.core_circle
     *
     * @mbggenerated Sun Sep 18 11:36:00 CST 2016
     */
    public void setCoreCircle(String coreCircle) {
        this.coreCircle = coreCircle == null ? null : coreCircle.trim();
    }
}