package com.me2me.live.model;

import java.util.Date;

import com.me2me.common.web.BaseEntity;

public class TopicData implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.topic_id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.steal_price
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer stealPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_time
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.diligently
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Double diligently;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.approve
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Double approve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_text_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateTextLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_text_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateTextCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_image_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateImageCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_vedio_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateVedioCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_vedio_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateVedioLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_audio_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateAudioCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_audio_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateAudioLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_vote_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateVoteCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_tease_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateTeaseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.update_day_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer updateDayCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.review_text_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer reviewTextCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_data.review_text_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer reviewTextLength;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.id
     *
     * @return the value of topic_data.id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.id
     *
     * @param id the value for topic_data.id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.topic_id
     *
     * @return the value of topic_data.topic_id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.topic_id
     *
     * @param topicId the value for topic_data.topic_id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.steal_price
     *
     * @return the value of topic_data.steal_price
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getStealPrice() {
        return stealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.steal_price
     *
     * @param stealPrice the value for topic_data.steal_price
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setStealPrice(Integer stealPrice) {
        this.stealPrice = stealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_time
     *
     * @return the value of topic_data.update_time
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_time
     *
     * @param updateTime the value for topic_data.update_time
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.diligently
     *
     * @return the value of topic_data.diligently
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Double getDiligently() {
        return diligently;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.diligently
     *
     * @param diligently the value for topic_data.diligently
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setDiligently(Double diligently) {
        this.diligently = diligently;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.approve
     *
     * @return the value of topic_data.approve
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Double getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.approve
     *
     * @param approve the value for topic_data.approve
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setApprove(Double approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_text_length
     *
     * @return the value of topic_data.update_text_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateTextLength() {
        return updateTextLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_text_length
     *
     * @param updateTextLength the value for topic_data.update_text_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateTextLength(Integer updateTextLength) {
        this.updateTextLength = updateTextLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_text_count
     *
     * @return the value of topic_data.update_text_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateTextCount() {
        return updateTextCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_text_count
     *
     * @param updateTextCount the value for topic_data.update_text_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateTextCount(Integer updateTextCount) {
        this.updateTextCount = updateTextCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_image_count
     *
     * @return the value of topic_data.update_image_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateImageCount() {
        return updateImageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_image_count
     *
     * @param updateImageCount the value for topic_data.update_image_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateImageCount(Integer updateImageCount) {
        this.updateImageCount = updateImageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_vedio_count
     *
     * @return the value of topic_data.update_vedio_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateVedioCount() {
        return updateVedioCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_vedio_count
     *
     * @param updateVedioCount the value for topic_data.update_vedio_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateVedioCount(Integer updateVedioCount) {
        this.updateVedioCount = updateVedioCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_vedio_length
     *
     * @return the value of topic_data.update_vedio_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateVedioLength() {
        return updateVedioLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_vedio_length
     *
     * @param updateVedioLength the value for topic_data.update_vedio_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateVedioLength(Integer updateVedioLength) {
        this.updateVedioLength = updateVedioLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_audio_count
     *
     * @return the value of topic_data.update_audio_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateAudioCount() {
        return updateAudioCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_audio_count
     *
     * @param updateAudioCount the value for topic_data.update_audio_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateAudioCount(Integer updateAudioCount) {
        this.updateAudioCount = updateAudioCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_audio_length
     *
     * @return the value of topic_data.update_audio_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateAudioLength() {
        return updateAudioLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_audio_length
     *
     * @param updateAudioLength the value for topic_data.update_audio_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateAudioLength(Integer updateAudioLength) {
        this.updateAudioLength = updateAudioLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_vote_count
     *
     * @return the value of topic_data.update_vote_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateVoteCount() {
        return updateVoteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_vote_count
     *
     * @param updateVoteCount the value for topic_data.update_vote_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateVoteCount(Integer updateVoteCount) {
        this.updateVoteCount = updateVoteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_tease_count
     *
     * @return the value of topic_data.update_tease_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateTeaseCount() {
        return updateTeaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_tease_count
     *
     * @param updateTeaseCount the value for topic_data.update_tease_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateTeaseCount(Integer updateTeaseCount) {
        this.updateTeaseCount = updateTeaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.update_day_count
     *
     * @return the value of topic_data.update_day_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getUpdateDayCount() {
        return updateDayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.update_day_count
     *
     * @param updateDayCount the value for topic_data.update_day_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setUpdateDayCount(Integer updateDayCount) {
        this.updateDayCount = updateDayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.review_text_count
     *
     * @return the value of topic_data.review_text_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getReviewTextCount() {
        return reviewTextCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.review_text_count
     *
     * @param reviewTextCount the value for topic_data.review_text_count
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setReviewTextCount(Integer reviewTextCount) {
        this.reviewTextCount = reviewTextCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_data.review_text_length
     *
     * @return the value of topic_data.review_text_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getReviewTextLength() {
        return reviewTextLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_data.review_text_length
     *
     * @param reviewTextLength the value for topic_data.review_text_length
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setReviewTextLength(Integer reviewTextLength) {
        this.reviewTextLength = reviewTextLength;
    }
}