package com.me2me.live.model;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.uid
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.live_image
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    private String liveImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.create_time
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.uid
     *
     * @return the value of topic.uid
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.uid
     *
     * @param uid the value for topic.uid
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.live_image
     *
     * @return the value of topic.live_image
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public String getLiveImage() {
        return liveImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.live_image
     *
     * @param liveImage the value for topic.live_image
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public void setLiveImage(String liveImage) {
        this.liveImage = liveImage == null ? null : liveImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.create_time
     *
     * @return the value of topic.create_time
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.create_time
     *
     * @param createTime the value for topic.create_time
     *
     * @mbggenerated Mon Apr 11 21:50:04 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}