package com.me2me.live.model;

import java.util.Date;

public class TopicFragment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment.id
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment.topic_id
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment.fragment_image
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    private String fragmentImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment.type
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment.content_type
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    private Integer contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment.create_time
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment.fragment
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    private String fragment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment.id
     *
     * @return the value of topic_fragment.id
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment.id
     *
     * @param id the value for topic_fragment.id
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment.topic_id
     *
     * @return the value of topic_fragment.topic_id
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment.topic_id
     *
     * @param topicId the value for topic_fragment.topic_id
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment.fragment_image
     *
     * @return the value of topic_fragment.fragment_image
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public String getFragmentImage() {
        return fragmentImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment.fragment_image
     *
     * @param fragmentImage the value for topic_fragment.fragment_image
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public void setFragmentImage(String fragmentImage) {
        this.fragmentImage = fragmentImage == null ? null : fragmentImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment.type
     *
     * @return the value of topic_fragment.type
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment.type
     *
     * @param type the value for topic_fragment.type
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment.content_type
     *
     * @return the value of topic_fragment.content_type
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public Integer getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment.content_type
     *
     * @param contentType the value for topic_fragment.content_type
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment.create_time
     *
     * @return the value of topic_fragment.create_time
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment.create_time
     *
     * @param createTime the value for topic_fragment.create_time
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment.fragment
     *
     * @return the value of topic_fragment.fragment
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public String getFragment() {
        return fragment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment.fragment
     *
     * @param fragment the value for topic_fragment.fragment
     *
     * @mbggenerated Mon Apr 11 17:47:00 CST 2016
     */
    public void setFragment(String fragment) {
        this.fragment = fragment == null ? null : fragment.trim();
    }
}