package com.me2me.live.mapper;

import com.me2me.live.model.LiveCpi;
import com.me2me.live.model.LiveCpiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveCpiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    int countByExample(LiveCpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    int deleteByExample(LiveCpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    int insert(LiveCpi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    int insertSelective(LiveCpi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    List<LiveCpi> selectByExample(LiveCpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    LiveCpi selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") LiveCpi record, @Param("example") LiveCpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    int updateByExample(@Param("record") LiveCpi record, @Param("example") LiveCpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    int updateByPrimaryKeySelective(LiveCpi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_cpi
     *
     * @mbggenerated Mon Apr 18 17:23:24 CST 2016
     */
    int updateByPrimaryKey(LiveCpi record);
}