package com.me2me.live.mapper;

import com.me2me.live.model.TopicDroparound;
import com.me2me.live.model.TopicDroparoundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicDroparoundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int countByExample(TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int deleteByExample(TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int insert(TopicDroparound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int insertSelective(TopicDroparound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    List<TopicDroparound> selectByExample(TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    TopicDroparound selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") TopicDroparound record, @Param("example") TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int updateByExample(@Param("record") TopicDroparound record, @Param("example") TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int updateByPrimaryKeySelective(TopicDroparound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int updateByPrimaryKey(TopicDroparound record);
}