package com.me2me.live.mapper;

import com.me2me.live.dto.GetLiveDetailDto;
import com.me2me.live.dto.GetLiveUpdateDto;
import com.me2me.live.model.TopicFragment;
import com.me2me.live.model.TopicFragmentExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TopicFragmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int countByExample(TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int deleteByExample(TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int insert(TopicFragment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int insertSelective(TopicFragment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    List<TopicFragment> selectByExampleWithBLOBs(TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    List<TopicFragment> selectByExample(TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    TopicFragment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") TopicFragment record, @Param("example") TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") TopicFragment record, @Param("example") TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int updateByExample(@Param("record") TopicFragment record, @Param("example") TopicFragmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int updateByPrimaryKeySelective(TopicFragment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TopicFragment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment
     *
     * @mbggenerated Mon Sep 26 17:20:17 CST 2016
     */
    int updateByPrimaryKey(TopicFragment record);

    Map<String,Long> countFragmentByTopicIdWithSince(GetLiveUpdateDto getLiveUpdateDto);

    List<TopicFragment> getTopicFragmentForPage(GetLiveDetailDto getLiveDetailDto);

    TopicFragment getFragmentByAT(Map map);
    /**
     * 取指定月的图片，for 图库
     * @author zhangjiwei
     * @date May 12, 2017
     * @param month  yyyy-MM
     * @return
     */
    List<TopicFragment> getImgFragmentByMonth(@Param("topicId")long topicId,@Param("month")String month);

}