package com.me2me.activity.model;

public class ActivityWithBLOBs extends Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_content
     *
     * @mbggenerated Thu Apr 28 20:13:14 CST 2016
     */
    private String activityContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_notice
     *
     * @mbggenerated Thu Apr 28 20:13:14 CST 2016
     */
    private String activityNotice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_content
     *
     * @return the value of activity.activity_content
     *
     * @mbggenerated Thu Apr 28 20:13:14 CST 2016
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_content
     *
     * @param activityContent the value for activity.activity_content
     *
     * @mbggenerated Thu Apr 28 20:13:14 CST 2016
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent == null ? null : activityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_notice
     *
     * @return the value of activity.activity_notice
     *
     * @mbggenerated Thu Apr 28 20:13:14 CST 2016
     */
    public String getActivityNotice() {
        return activityNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_notice
     *
     * @param activityNotice the value for activity.activity_notice
     *
     * @mbggenerated Thu Apr 28 20:13:14 CST 2016
     */
    public void setActivityNotice(String activityNotice) {
        this.activityNotice = activityNotice == null ? null : activityNotice.trim();
    }
}