package com.me2me.activity.model;

import com.me2me.common.web.BaseEntity;

public class AmiliData implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_mili_data.id
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_mili_data.key
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_mili_data.type
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_mili_data.link_url
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_mili_data.orderby
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    private Integer orderby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_mili_data.status
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_mili_data.content
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_mili_data.id
     *
     * @return the value of a_mili_data.id
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_mili_data.id
     *
     * @param id the value for a_mili_data.id
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_mili_data.key
     *
     * @return the value of a_mili_data.key
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_mili_data.key
     *
     * @param key the value for a_mili_data.key
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_mili_data.type
     *
     * @return the value of a_mili_data.type
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_mili_data.type
     *
     * @param type the value for a_mili_data.type
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_mili_data.link_url
     *
     * @return the value of a_mili_data.link_url
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_mili_data.link_url
     *
     * @param linkUrl the value for a_mili_data.link_url
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_mili_data.orderby
     *
     * @return the value of a_mili_data.orderby
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_mili_data.orderby
     *
     * @param orderby the value for a_mili_data.orderby
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_mili_data.status
     *
     * @return the value of a_mili_data.status
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_mili_data.status
     *
     * @param status the value for a_mili_data.status
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_mili_data.content
     *
     * @return the value of a_mili_data.content
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_mili_data.content
     *
     * @param content the value for a_mili_data.content
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}