package com.me2me.activity.mapper;

import com.me2me.activity.model.AmiliData;
import com.me2me.activity.model.AmiliDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AmiliDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int countByExample(AmiliDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int deleteByExample(AmiliDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int insert(AmiliData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int insertSelective(AmiliData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    List<AmiliData> selectByExampleWithBLOBs(AmiliDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    List<AmiliData> selectByExample(AmiliDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    AmiliData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") AmiliData record, @Param("example") AmiliDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") AmiliData record, @Param("example") AmiliDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int updateByExample(@Param("record") AmiliData record, @Param("example") AmiliDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int updateByPrimaryKeySelective(AmiliData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(AmiliData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_mili_data
     *
     * @mbggenerated Mon Dec 12 10:23:59 CST 2016
     */
    int updateByPrimaryKey(AmiliData record);
}