package com.me2me.activity.mapper;

import com.me2me.activity.model.Atask;
import com.me2me.activity.model.AtaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AtaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int countByExample(AtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int deleteByExample(AtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int insert(Atask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int insertSelective(Atask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    List<Atask> selectByExampleWithBLOBs(AtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    List<Atask> selectByExample(AtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    Atask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") Atask record, @Param("example") AtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") Atask record, @Param("example") AtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int updateByExample(@Param("record") Atask record, @Param("example") AtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int updateByPrimaryKeySelective(Atask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Atask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_task
     *
     * @mbggenerated Wed Dec 14 20:55:41 CST 2016
     */
    int updateByPrimaryKey(Atask record);
}