package com.me2me.user.mapper;

import com.me2me.user.model.emotionRecord;
import com.me2me.user.model.emotionRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface emotionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int countByExample(emotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int deleteByExample(emotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int insert(emotionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int insertSelective(emotionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    List<emotionRecord> selectByExample(emotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    emotionRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") emotionRecord record, @Param("example") emotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int updateByExample(@Param("record") emotionRecord record, @Param("example") emotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int updateByPrimaryKeySelective(emotionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int updateByPrimaryKey(emotionRecord record);
}