package com.me2me.user.mapper;

import com.me2me.user.model.UserTsoken;
import com.me2me.user.model.UserTsokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTsokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    int countByExample(UserTsokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    int deleteByExample(UserTsokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    int insert(UserTsoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    int insertSelective(UserTsoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    List<UserTsoken> selectByExample(UserTsokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    UserTsoken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserTsoken record, @Param("example") UserTsokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    int updateByExample(@Param("record") UserTsoken record, @Param("example") UserTsokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    int updateByPrimaryKeySelective(UserTsoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Mon Feb 29 16:27:09 CST 2016
     */
    int updateByPrimaryKey(UserTsoken record);
}